<a href="https://colab.research.google.com/github/RoseJaisil/CNN/blob/main/2D_Convolve.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import libraries

In [14]:
import numpy as np
import scipy.signal as sc

# Create 2d conv function

In [18]:
def conv2d(X, W, p=(0, 0), s=(1,1)):
  """
  X - 2D list
  W - 2D filter
  p - padding size in 2D
  s - stride in 2D
  
  convolution type = same
  """
  W_rot = np.array(W)[::-1, ::-1] # convert the filter to array and rotate
  X_orig = np.array(X) # convert it to array

  n1 = X_orig.shape[0] + 2*p[0] # height of the output image
  n2 = X_orig.shape[1] + 2*p[1] # width of the output image

  X_padded = np.zeros(shape=(n1,n2)) # zeros of shape equivalent to the output image
  X_padded[p[0]:p[0]+X_orig.shape[0], p[1]:p[1]+X_orig.shape[1]] = X_orig # fitting the input image to the center part of the zero matrix

  res =[] # list to collect convolution result for each window
  for i in range(0, int((X_padded.shape[0] - W_rot.shape[0])/s[0])+1, s[0]): # in the height dim
    res.append([]) # tips to make the list to 2D 

    for j in range(0, int((X_padded.shape[1] - W_rot.shape[1])/s[1])+1, s[1]):
      # take out a chunk from the image
      X_sub = X_padded[i:i+W_rot.shape[0], j:j+W_rot.shape[1]]

      # Convolution 
      res[-1].append(np.sum(X_sub * W_rot)) # elementwise multiplication and then sum it up

  return(np.array(res))


# Testing

In [19]:
# Input 2D list
X= [[1, 3, 2, 4], [5, 6, 1, 3], [1, 2, 0, 2], [3, 4, 3, 2]]
W = [[1, 0 ,3], [1, 2, 1], [0, 1, 1]]

# Custom built convolution function
print('conv2d function implementation:',
      conv2d(X, W, p=(1,1), s=(1,1)))

# Scipy convolution function
print("Scipy function implementation",
      sc.convolve2d(X, W, mode='same'))

conv2d function implementation: [[11. 25. 32. 13.]
 [19. 25. 24. 13.]
 [13. 28. 25. 17.]
 [11. 17. 14.  9.]]
Scipy function implementation [[11 25 32 13]
 [19 25 24 13]
 [13 28 25 17]
 [11 17 14  9]]
